filedog:
  alioss:
    endpoint: *****
    access-key-id: *****
    access-key-secret: *****
    bucket-name: *****
  redis:
    host: 39.101.140.144
    port: 6379
    password: 200212
    database: 0
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://*****:3306/filedog?serverTimezone=Asia/Shanghai
    username: root
    password: 200212
